name: bearer_token_package
description: A package that generates a ready-made Bearer Token for you based on a secret key.
version: 1.0.1
repository: https://github.com/ShoshiDeveloper/bearer_token_package
homepage: https://pub.dev/packages/bearer_token_package

environment:
  sdk: ">=3.4.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.3
  encrypt: ^5.0.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
